# 00 PyTorch Fundamentals
- Resource Notebook: - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [4]:
print(torch.__version__)

2.1.2+cu121


## 1. Introduction to Tensors
### Creating tensors.

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
##Getting tensors back as an integer.
scalar.item()

7

In [16]:
#Creating a vector/matrix.
vector = torch.tensor([[7,7], [7,7]])
vector.ndim

2

In [17]:
vector.shape

torch.Size([2, 2])

In [18]:
#Random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9329, 0.7052, 0.3304, 0.7412],
        [0.7046, 0.8188, 0.7681, 0.9647],
        [0.4508, 0.3627, 0.8901, 0.1845]])

### Tensor of zeroes

In [20]:
zero = torch.zeros(size=(3,3)) #Doesnt matter if you add size argument or not.
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor of ones

In [21]:
one = torch.ones(3,3)
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Tensors and tensor-likes

In [22]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
one_to_ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])