# 00 PyTorch Fundamentals
- Resource Notebook: - https://www.learnpytorch.io/00_pytorch_fundamentals/

## 0. Importing Dependencies

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
print(torch.__version__)

2.1.2+cu121


## 1. Introduction to Tensors
### Creating tensors.

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
##Getting tensors back as an integer.
scalar.item()

7

In [5]:
#Creating a vector/matrix.
vector = torch.tensor([[7,7], [7,7]])
vector.ndim

2

In [6]:
vector.shape

torch.Size([2, 2])

In [7]:
#Random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5745, 0.1040, 0.0036, 0.0202],
        [0.5325, 0.5547, 0.9758, 0.4311],
        [0.5055, 0.8071, 0.4578, 0.0505]])

### Tensor of zeroes

In [8]:
zero = torch.zeros(size=(3,3)) #Doesnt matter if you add size argument or not.
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor of ones

In [9]:
one = torch.ones(3,3)
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### Tensors and tensor-likes

In [10]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
one_to_ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 2. Manipulating Tensors
- Addition
- Subtraction
- MUltipication (element wise)
- Division
- Matrix multiplication

In [12]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([5,6,7])

In [13]:
#Adding
tensor_1 + tensor_2

tensor([ 6,  8, 10])

In [14]:
#Subtracting
tensor_2 - tensor_1

tensor([4, 4, 4])

In [15]:
#Multiplication
tensor_1 * tensor_2

tensor([ 5, 12, 21])

In [16]:
#Division
tensor_2 / tensor_1

tensor([5.0000, 3.0000, 2.3333])

In [17]:
#Matrix Multiplication
m1 = torch.tensor([[1,2],[3,4]])
m2 = torch.tensor([[2,3], [4,5]])
torch.matmul(m1, m2)

tensor([[10, 13],
        [22, 29]])

## 3. Tensor Aggregation
- min
- max
- mean
- sum

In [18]:
tensor = torch.arange(10, 110, 10)
tensor, tensor.dtype

(tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), torch.int64)

In [19]:
torch.min(tensor)

tensor(10)

In [20]:
torch.max(tensor)

tensor(100)

In [21]:
torch.mean(tensor.type(torch.float32)) #As torch.mean takes in float or complex data types and not long data types (int64)

tensor(55.)

In [22]:
torch.sum(tensor)

tensor(550)

## 4. Reshaping Tensors
- Reshape: - Reshapes the tensor to desired shape
- View: - VIew the tensor of certain shape but keep the same memory as the original one.
- Stacking: - Stacking tensors on top of each other.
- Squeeze: -  Removes all `1` dimensions from a tensor.
- Unsqueeze: - Adds `1` dimension to a tensor.
- Permute: - View the tensor with dimensions permuted in a certain way.

In [23]:
x = torch.arange(1,10)
x, x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), 1)

In [24]:
x_reshape = x.reshape(3,3)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [29]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [34]:
x_stack = torch.stack([x,x*4,x-1], dim=0)
x_stack, x_stack.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
         [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
         [ 0,  1,  2,  3,  4,  5,  6,  7,  8]]),
 torch.Size([3, 9]))